name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use v4 for better stability

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Updated to LTS version

      - name: Install dependencies
        run: npm ci  # Use npm ci for cleaner installs in CI

      - name: Run tests
        run: npm test